name: test lib

on: [pull_request]

jobs:
  test:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        node-version: ['10.x', '12.10.x']
        platform: [ubuntu-latest, macos-latest, windows-latest]
        runner: [npm, yarn]
        include:
          - platform: ubuntu-latest
            browser: chrome
            return-node-version: ls $RUNNER_TOOL_CACHE/node
          - platform: windows-latest
            browser: chrome
            return-node-version: gci C:\hostedtoolcache\windows\node |% FullName
          - platform: macos-latest
            browser: electron
            return-node-version: ls $RUNNER_TOOL_CACHE/node

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 3
    - name: build
      run: |
           cd ./lib/rust
           cargo build --verbose
