name: test library

on: [pull_request]

jobs:
  test-lib:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 3
    - name: build
      run: |
           cd ./lib/rust
           cargo build --verbose
